/**
 * Push Article #9 to Firebase Firestore
 * Run: node scripts/push_article_9.mjs
 */

import { initializeApp } from "firebase/app";
import { getFirestore, doc, setDoc } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyALi7uZIVIYO_Tomfc0PFDzV-YBMr5XFRg",
  authDomain: "groworbit-9b75a.firebaseapp.com",
  projectId: "groworbit-9b75a",
  storageBucket: "groworbit-9b75a.firebasestorage.app",
  messagingSenderId: "729990203843",
  appId: "1:729990203843:web:5f84f4989c87d452de1576",
  measurementId: "G-6TGTYN8XX4",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const articleData = {
  slug: "amazon-product-infographic-design",
  title: "Feature Dumping Is Killing Your Conversion Rate: How to Design Clean Amazon Infographics",
  excerpt: "Learn how to design clean Amazon product infographics, reduce feature dumping and create clearer, more scannable listing images.",
  category: "Listing Optimization",
  tags: ["amazon infographics", "infographic design", "listing optimization", "product images", "conversion rate"],
  coverImage: "/images/article image/9/amazon-product-infographic-design.avif",
  date: new Date().toISOString().split("T")[0],
  readTime: "14 min read",
  author: {
    name: "Talha Waseem",
    role: "Technical Strategist",
    avatar: null,
  },
  status: "published",
  featured: false,
  views: 0,
  content: [
    { type: "paragraph", text: "A secondary Amazon image should explain something the shopper could not understand from the MAIN image alone." },
    { type: "paragraph", text: "Instead, many listings turn every available image into a specification sheet." },
    { type: "paragraph", text: "Ten features. Six icons. Three arrows. Multiple text blocks. Tiny labels." },
    { type: "paragraph", text: "Everything may be technically relevant." },
    { type: "paragraph", text: "Very little is easy to process." },
    { type: "paragraph", text: "Amazon's own product photography guidance recommends using different image types to communicate different aspects of the product, including lifestyle, scale and detailed shots. It also emphasizes that product images should be accurate, clear and useful to shoppers ([sell.amazon.com](https://sell.amazon.com/blog/product-photos))." },
    { type: "paragraph", text: "That creates a useful distinction:" },
    { type: "paragraph", text: "A good infographic does not communicate everything. It communicates the right thing clearly." },
    { type: "paragraph", text: "That is the foundation of effective **amazon product infographic design**." },
    { type: "divider", text: "" },

    { type: "heading", text: "The Cognitive Overload Problem: Why More Information Can Mean Less Clarity" },
    { type: "paragraph", text: "There is a temptation to believe that more information automatically makes an image more persuasive." },
    { type: "paragraph", text: "It does not." },
    { type: "paragraph", text: "When several elements compete for attention, the shopper has to spend more effort figuring out:\n\n* What should I look at first?\n* Which feature matters most?\n* What does this diagram mean?\n* Which number is important?\n* How are these elements related?" },
    { type: "paragraph", text: "Hick's law is relevant here, but it needs to be used carefully." },
    { type: "paragraph", text: "Hick's law describes a relationship between choice reaction time and the number of stimulus-response alternatives, or the amount of uncertainty in a task. The 2018 review by Proctor and Schneider also discusses the law's limitations and the conditions under which it applies ([Proctor & Schneider, 2018](https://journals.sagepub.com/doi/10.1080/17470218.2017.1322622))." },
    { type: "paragraph", text: "That does not mean every extra element on an Amazon image directly reduces conversion." },
    { type: "paragraph", text: "Amazon listing images are not controlled choice-reaction experiments." },
    { type: "paragraph", text: "The practical design lesson is narrower:" },
    { type: "paragraph", text: "When too many visual elements compete for attention, the path to the important information becomes less obvious." },
    { type: "paragraph", text: "This matters even more on smaller screens. Baymard's mobile product-page research found that mobile designs can make it difficult for users to get a complete overview, causing some users to overlook important product images or entire sections of page content ([Baymard](https://baymard.com/mcommerce-usability/benchmark/mobile-page-types/product-page))." },
    { type: "paragraph", text: "The answer is not to remove useful information." },
    { type: "paragraph", text: "It is to organize it better." },
    { type: "divider", text: "" },

    { type: "heading", text: "What Is Feature Dumping vs. Benefit-Led Infographic Design?" },
    { type: "paragraph", text: "Feature dumping happens when an infographic tries to communicate every available product fact instead of selecting the information that matters most for that image." },
    { type: "paragraph", text: "Consider a reusable bottle." },
    { type: "heading-h3", text: "Feature-dumped version" },
    { type: "list", text: "* 304 Stainless Steel\n* Double-Wall Vacuum Insulation\n* BPA Free\n* Leakproof Lid\n* Wide Mouth\n* 24 oz Capacity\n* Powder Coating\n* Non-Slip Base\n* Reusable\n* Dishwasher Safe\n* Cold Retention\n* Hot Retention" },
    { type: "paragraph", text: "Nothing here is necessarily wrong." },
    { type: "paragraph", text: "The problem is that the shopper has to work out what matters most." },
    { type: "heading-h3", text: "Benefit-led version" },
    { type: "paragraph", text: "**KEEPS DRINKS COLD FOR HOURS**" },
    { type: "paragraph", text: "Double-wall insulation helps reduce temperature transfer during everyday use." },
    { type: "paragraph", text: "Then use the product visual to show the construction." },
    { type: "paragraph", text: "The second version gives the shopper a clear starting point." },
    { type: "paragraph", text: "The first gives them a specification database." },
    { type: "heading-h3", text: "Features Tell. Benefits Give the Feature a Job." },
    { type: "paragraph", text: "A feature answers: *What does the product have?*" },
    { type: "paragraph", text: "A benefit answers: *Why should I care?*" },
    { type: "table", text: "| Feature | Benefit |\n|:---|:---|\n| 304 stainless steel | Durable construction for repeated daily use |\n| 180 degree adjustable hinge | Position the display at the angle you need |\n| 4-liter capacity | Hold more without frequent refills |" },
    { type: "paragraph", text: "The benefit must remain faithful to the actual feature. You should not turn a technical specification into a claim that the product cannot reasonably support." },
    { type: "paragraph", text: "A useful design workflow is:" },
    { type: "list", text: "1. Start with the feature\n2. Identify the shopper question it answers\n3. Translate into a practical benefit\n4. Pair with visual proof" },
    { type: "paragraph", text: "That turns specifications into communication." },
    { type: "divider", text: "" },

    { type: "heading", text: "The Three Rules for Designing Cleaner Amazon Infographics" },
    { type: "heading-h3", text: "Rule 1: Give Every Slide One Core Message" },
    { type: "paragraph", text: "This is the most useful rule in the entire framework:" },
    { type: "paragraph", text: "**One slide, one primary idea.**" },
    { type: "paragraph", text: "That does not mean one sentence. It means one dominant reason for the image to exist." },
    { type: "paragraph", text: "For example:" },
    { type: "paragraph", text: "**24-HOUR COLD RETENTION**" },
    { type: "paragraph", text: "The supporting copy can explain the insulation. The product render can show the double-wall construction. A small callout can identify the relevant component." },
    { type: "paragraph", text: "Everything serves the central message." },
    { type: "paragraph", text: "Do not make that same image simultaneously responsible for:" },
    { type: "list", text: "* Capacity\n* Materials\n* Cleaning\n* Lid design\n* Carrying handle\n* Temperature retention\n* Warranty" },
    { type: "paragraph", text: "Those topics can be handled elsewhere in the gallery." },
    { type: "paragraph", text: "Amazon's own photography guidance recommends using different shot types to highlight different product features and use cases rather than making every image do the same job ([sell.amazon.com](https://sell.amazon.com/blog/product-photos))." },
    { type: "heading-h4", text: "The two-second test" },
    { type: "paragraph", text: "The two-second test is a design heuristic, not an Amazon benchmark." },
    { type: "paragraph", text: "Look at the image briefly. Can you identify:" },
    { type: "list", text: "* The product?\n* The main message?\n* The visual evidence supporting it?" },
    { type: "paragraph", text: "If you cannot, simplify." },

    { type: "heading-h3", text: "Rule 2: Build a Clear Visual Hierarchy" },
    { type: "paragraph", text: "Good **Amazon infographics** tell the eye where to start." },
    { type: "paragraph", text: "A simple hierarchy follows this order: headline, then the product, then the key visual, then supporting detail." },
    { type: "paragraph", text: "For example:" },
    { type: "paragraph", text: "**BUILT FOR HEAVY DAILY USE**" },
    { type: "list", text: "1. Large product render\n2. Close-up showing the reinforced component\n3. Small material specification" },
    { type: "paragraph", text: "The shopper should not have to choose between eight elements that all have equal visual weight." },
    { type: "heading-h4", text: "Contrast creates hierarchy" },
    { type: "paragraph", text: "Use size, weight, position, whitespace, color, typography and scale to establish importance." },
    { type: "paragraph", text: "The strongest visual element should generally communicate the primary message." },
    { type: "paragraph", text: "If the headline, product, icons and specification numbers are all equally prominent, the hierarchy has collapsed." },
    { type: "heading-h4", text: "Custom Iconography Beats Random Clipart" },
    { type: "paragraph", text: "Icons can make complex information easier to scan." },
    { type: "paragraph", text: "But unrelated stock icons can make a premium listing look assembled rather than designed." },
    { type: "paragraph", text: "Imagine an infographic using:" },
    { type: "list", text: "* A battery icon from one icon family\n* A shield from another\n* A water droplet from a third\n* A material icon with a completely different stroke style" },
    { type: "paragraph", text: "The information may be correct." },
    { type: "paragraph", text: "The visual system feels inconsistent." },
    { type: "paragraph", text: "A better icon system keeps:" },
    { type: "list", text: "* Similar stroke weight\n* Consistent corner treatment\n* Similar perspective\n* Consistent level of detail\n* Similar visual scale" },
    { type: "paragraph", text: "Icons should support the information. They should not become the visual attraction." },

    { type: "heading-h3", text: "Rule 3: Keep the Text Tight, Not Artificially Short" },
    { type: "paragraph", text: "There is no universal Amazon rule saying that secondary images must contain 15 words or fewer." },
    { type: "paragraph", text: "The 15-word guideline is better treated as a creative constraint. Its purpose is to force prioritization." },
    { type: "paragraph", text: "A practical structure is:" },
    { type: "list", text: "* **Headline:** 3 to 5 words\n* **Supporting copy:** One short sentence or phrase\n* **Callouts:** Short labels rather than mini paragraphs" },
    { type: "paragraph", text: "For example:" },
    { type: "paragraph", text: "**ERGONOMIC GRIP**" },
    { type: "paragraph", text: "Contoured handle for more comfortable extended use." },
    { type: "paragraph", text: "That is enough for many image contexts." },
    { type: "paragraph", text: "Compare that with a paragraph explaining the handle's complete construction, material, manufacturing process and ergonomic design philosophy." },
    { type: "paragraph", text: "The longer version may contain more information." },
    { type: "paragraph", text: "The shorter version is more likely to be understood while a shopper is scanning the gallery." },
    { type: "divider", text: "" },

    { type: "heading", text: "Audit Your Existing Amazon Infographics for Feature Dumping" },
    { type: "paragraph", text: "Open your current gallery and inspect every infographic. Start counting." },
    { type: "paragraph", text: "**Text:** How many separate text blocks are there?" },
    { type: "paragraph", text: "**Features:** How many different product claims are being communicated?" },
    { type: "paragraph", text: "**Visual elements:** How many icons, arrows, badges and callouts compete for attention?" },
    { type: "paragraph", text: "**Hierarchy:** Can you identify the primary message immediately?" },
    { type: "paragraph", text: "Then ask:" },
    { type: "paragraph", text: "If I had to remove half of this image, what would stay?" },
    { type: "paragraph", text: "That question exposes weak prioritization quickly." },
    { type: "paragraph", text: "A useful rule is: if removing an element does not make the shopper lose important information, consider removing it." },
    { type: "paragraph", text: "The objective is not to make the image empty. It is to make every remaining element earn its space." },
    { type: "divider", text: "" },

    { type: "heading", text: "How 3D Renders Can Reduce Visual Noise" },
    { type: "paragraph", text: "Technical products create a special problem." },
    { type: "paragraph", text: "The product itself often contains the information you need to explain." },
    { type: "paragraph", text: "If you place six arrows and multiple labels over a normal product photograph, the image can become difficult to follow." },
    { type: "paragraph", text: "This is where 3D rendering can be useful." },
    { type: "paragraph", text: "Instead of covering one photograph with callouts, create a controlled exploded view." },
    { type: "paragraph", text: "For example:" },
    { type: "list", text: "1. Outer shell\n2. Insulation layer\n3. Internal component\n4. Base assembly" },
    { type: "paragraph", text: "Now the visual itself explains the physical relationship between the parts." },
    { type: "paragraph", text: "This is where **3D rendering infographic callouts** become useful. The render is not simply decoration. It becomes part of the explanation." },
    { type: "divider", text: "" },

    { type: "heading", text: "Example: Turning a Feature Dump Into a Clean Infographic" },
    { type: "paragraph", text: "Imagine a rechargeable desk lamp." },
    { type: "heading-h3", text: "Feature-dumped image (all on one slide)" },
    { type: "list", text: "* 4000 mAh battery\n* 3 brightness modes\n* Touch controls\n* 4000K color temperature\n* USB-C\n* Aluminum body\n* Foldable design\n* 180 degree rotation\n* 8-hour runtime\n* LED technology\n* Anti-slip base" },
    { type: "paragraph", text: "That is a lot of information for one frame." },
    { type: "paragraph", text: "Instead, distribute the information across the gallery." },
    { type: "table", text: "| Image | Focus | Content |\n|:---|:---|:---|\n| Image 1 | MAIN product image | Clean white-background product photo |\n| Image 2 | LIGHT WHERE YOU NEED IT | Show the lamp in a realistic desk setup |\n| Image 3 | 180 DEGREE FLEXIBLE POSITIONING | Show the hinge and range of movement |\n| Image 4 | UP TO 8 HOURS OF USE | Communicate the relevant battery information |\n| Image 5 | THREE LIGHTING MODES | Show the available modes visually |\n| Image 6 | BUILT FOR EVERYDAY USE | Detailed render showing construction and materials |\n| Image 7 | Technical specifications | Dimensions, charging information and technical specifications |" },
    { type: "paragraph", text: "The information did not disappear. It was reorganized around different shopper questions." },
    { type: "paragraph", text: "That is a much stronger approach to a **clean Amazon product infographic** strategy." },
    { type: "divider", text: "" },

    { type: "heading", text: "Clean Infographics Are Part of Listing Conversion Optimization" },
    { type: "paragraph", text: "Infographics should not be designed independently from the rest of the listing." },
    { type: "paragraph", text: "The title already communicates certain information. The bullets communicate more. The image gallery should provide visual evidence and explanation. A+ Content can provide deeper brand and product storytelling." },
    { type: "paragraph", text: "That means a good infographic should not simply repeat a bullet point in larger text. It can show what the bullet describes." },
    { type: "paragraph", text: "For example:" },
    { type: "list", text: "* **Bullet:** Reinforced aluminum frame.\n* **Image:** Close-up 3D visualization showing the frame structure." },
    { type: "paragraph", text: "That is more useful than simply writing REINFORCED ALUMINUM FRAME over a generic product photo." },
    { type: "paragraph", text: "This is where listing conversion optimization intersects with creative production." },
    { type: "paragraph", text: "The question is not: *How much information can we put on the image?*" },
    { type: "paragraph", text: "It is: *What information is easiest to understand visually?*" },
    { type: "paragraph", text: "For the broader system, see our [Amazon infographic design](/service/listing-optimization) service." },
    { type: "divider", text: "" },

    { type: "heading", text: "A Practical Infographic Formula" },
    { type: "paragraph", text: "Before designing a slide, write down five things." },
    { type: "table", text: "| Step | Question |\n|:---|:---|\n| Shopper question | What does the shopper want to know? |\n| Main answer | What is the single most important takeaway? |\n| Visual proof | What should they see? |\n| Supporting detail | What small amount of text is actually necessary? |\n| Accuracy check | Does the visual represent the actual product? |" },
    { type: "heading-h3", text: "Example" },
    { type: "list", text: "* **Shopper question:** Will this organizer fit under my desk?\n* **Main answer:** Compact under-desk storage\n* **Visual proof:** Product positioned beneath a desk\n* **Supporting detail:** Accurate height and width\n* **Accuracy check:** Dimensions and perspective must match the actual product" },
    { type: "paragraph", text: "Now you have a creative brief. You do not need ten icons to begin designing." },
    { type: "divider", text: "" },

    { type: "heading", text: "Common Amazon Product Feature Infographic Mistakes" },
    { type: "paragraph", text: "**Putting specifications before the main benefit.** Specifications matter. But the shopper needs context for why they matter. Lead with the practical reason before the technical explanation whenever appropriate." },
    { type: "paragraph", text: "**Using every available feature.** More information is not automatically more useful. Some information belongs in the bullets, another image, A+ Content or the product description." },
    { type: "paragraph", text: "**Making every element equally prominent.** If every headline is large and every icon is bright, there is no clear starting point. Hierarchy disappears." },
    { type: "paragraph", text: "**Using decorative graphics with no communication purpose.** Arrows, circles, badges and shapes should help explain something. Decorative elements are fine. They become a problem when they compete with the product or message." },
    { type: "paragraph", text: "**Designing for desktop only.** An infographic that looks clean on a large monitor may become unreadable on a phone. Always inspect it at realistic mobile display size." },
    { type: "paragraph", text: "**Repeating the same message across several slides.** If Images 3, 4 and 5 all communicate the same feature, valuable visual space is being wasted. Give each image a different job." },
    { type: "divider", text: "" },

    { type: "heading", text: "The Clean Amazon Product Infographic Checklist" },
    { type: "heading-h3", text: "Message" },
    { type: "list", text: "* Is there one clear primary message?\n* Can I identify it quickly?\n* Does the image answer a real shopper question?" },
    { type: "heading-h3", text: "Hierarchy" },
    { type: "list", text: "* Is the headline dominant?\n* Is the product easy to identify?\n* Are secondary details visually subordinate?\n* Is there enough whitespace?" },
    { type: "heading-h3", text: "Text" },
    { type: "list", text: "* Is every word necessary?\n* Can a phrase replace a sentence?\n* Is the text readable on mobile?" },
    { type: "heading-h3", text: "Graphics" },
    { type: "list", text: "* Are icons visually consistent?\n* Do arrows and callouts explain something?\n* Are decorative elements competing with the message?" },
    { type: "heading-h3", text: "Product Accuracy" },
    { type: "list", text: "* Does the product match what is actually sold?\n* Are proportions and dimensions accurate?\n* Are the feature claims legitimate?" },
    { type: "heading-h3", text: "Gallery Role" },
    { type: "list", text: "* Does this image teach something the previous image did not?\n* Is another image already communicating the same idea?" },
    { type: "divider", text: "" },

    { type: "heading", text: "Frequently Asked Questions" },
    { type: "paragraph", text: "**What is feature dumping on Amazon infographics?**" },
    { type: "paragraph", text: "Feature dumping is the practice of placing too many product specifications, benefits, icons and claims into one image without establishing a clear primary message. The result can contain useful information while still being difficult to scan and understand." },
    { type: "paragraph", text: "**How do I design clean product feature infographics?**" },
    { type: "paragraph", text: "Start with one shopper question and one primary message. Then show the product clearly, establish visual hierarchy, use concise supporting copy and remove information that does not directly support the main idea." },
    { type: "paragraph", text: "**How much text should be on an Amazon product image?**" },
    { type: "paragraph", text: "Amazon does not publish a universal word-count limit for text on secondary product images. A useful design approach is to keep the headline around 3 to 5 words and use only the supporting text needed to explain the visual. The 15-word guideline is a creative constraint, not an Amazon requirement." },
    { type: "paragraph", text: "**Can Amazon infographics contain text?**" },
    { type: "paragraph", text: "Secondary listing images can communicate product features and benefits, but the MAIN image has significantly stricter requirements and cannot contain added text, graphics or similar promotional elements. Amazon recommends using additional images to show different features, angles and product use ([sellercentral.amazon.com](https://sellercentral.amazon.com/seller-forums/discussions/t/99a0dc92-15dc-492a-b24e-f327f4c28dd5))." },
    { type: "paragraph", text: "**Should every Amazon listing image be an infographic?**" },
    { type: "paragraph", text: "No. A strong gallery can combine MAIN product photography, lifestyle images, technical infographics, close-ups, comparisons, scale references and specifications. Each image should have a distinct job." },
    { type: "divider", text: "" },

    { type: "heading", text: "Final Takeaway" },
    { type: "paragraph", text: "A good Amazon infographic is not a compressed version of your product specification sheet." },
    { type: "paragraph", text: "It is a visual answer to a shopper's question." },
    { type: "paragraph", text: "One image should establish the main idea. The product should remain visible. The hierarchy should be obvious. The copy should be short enough to scan. The visual should prove the claim wherever possible." },
    { type: "paragraph", text: "And technical information should be distributed across the gallery instead of being forced into one overloaded slide." },
    { type: "paragraph", text: "That is the difference between feature dumping and purposeful Amazon creative." },
    { type: "paragraph", text: "When these principles are applied consistently, [Amazon infographic design](/service/listing-optimization) becomes part of a broader listing optimization system rather than another layer of text placed over a product photo." },
    { type: "divider", text: "" },
    { type: "paragraph", text: "*Written by Talha Waseem, Technical Strategist*" },
    { type: "paragraph", text: "*Last reviewed: September 2026*" },
    { type: "divider", text: "" },
    { type: "heading-h3", text: "Source standard used for this article" },
    { type: "paragraph", text: "Amazon first-party sources are used for Amazon-specific product-image requirements and recommendations, including the distinction between MAIN and additional images and the use of different image types to communicate features and product use ([sell.amazon.com](https://sell.amazon.com/blog/product-photos); [Amazon Seller Central](https://sellercentral.amazon.com/seller-forums/discussions/t/4b3c4c39-6f8c-4312-aa0e-99982eb8f5e1))." },
    { type: "paragraph", text: "Nielsen-style cognitive claims are not overstated: Hick's law is cited only as a general principle relating choice reaction time to the number of alternatives or uncertainty in a task, not as evidence that adding elements to an Amazon image directly reduces conversion ([Proctor & Schneider, 2018](https://journals.sagepub.com/doi/10.1080/17470218.2017.1322622))." },
    { type: "paragraph", text: "Baymard is used for ecommerce usability research around mobile product pages and product-image exploration. Its research found that 56% of users' first actions on product pages involved exploring product images, while its mobile research documents problems with overlooking content on small screens ([Baymard](https://baymard.com/research-articles/in-scale-product-images))." },
    { type: "paragraph", text: "The two-second scan test, one core message per slide, and 15-word guideline are presented as practical design heuristics, not Amazon requirements or universal scientific thresholds." },
  ],
};

async function pushArticle() {
  try {
    const postId = articleData.slug;
    await setDoc(doc(db, "blogs", postId), articleData);
    console.log(`Article #9 published to Firestore with ID: ${postId}`);
    console.log(`Live URL: https://www.groworbitofficial.com/blog/${articleData.slug}`);
    process.exit(0);
  } catch (error) {
    console.error("Failed to push article:", error);
    process.exit(1);
  }
}

pushArticle();
